########################
#        SERVER
########################
spring.application.name=kun-uz-step-by-step
server.port=8080
server.url=http://localhost:${server.port}
########################
#        DATABASE
########################
spring.datasource.url=jdbc:postgresql://localhost:5432/kunuz_db
spring.datasource.username=kunuz_User
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
########################
#        EMAIL
########################
spring.mail.host=smtp.mail.ru
spring.mail.port=465
spring.mail.username=jumaniyazov.bobur@mail.ru
spring.mail.password=Ep9SbVyxJB2ZDYelXQzj
spring.mail.protocol=smtps
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=50000
spring.mail.properties.mail.smtp.timeout=50000
spring.mail.properties.mail.smtp.writetimeout=50000
########################
#        SMS
########################
sms.eskiz.email=eskiz-dan-ro'yhatdan-o'tilgan-email
sms.eskiz.password=eskiz-taqdim-etilgan-password
########################
#        Attach
########################
attache.folder=attaches
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
