### Registration using Email
POST localhost:8080/api/v1/auth/registration
Content-Type: application/json

{
  "name": "Afandi",
  "surname": "Toshmatov",
  "username": "bigmangcom@gmail.com",
  "password": "12345"
}

### Email registration confirm
GET http://localhost:8080/api/v1/auth/registration/email/verification/bigmangcom@gmail.com/91557


### Registration using sms
POST localhost:8080/api/v1/auth/registration
Content-Type: application/json

{
  "name": "Afandi",
  "surname": "Toshmatov",
  "username": "+998910171231",
  "password": "12345"
}


### Registration using sms
PUT localhost:8080/api/v1/auth/registration/sms/verification
Content-Type: application/json

{
  "phoneNumber": "+998910171231",
  "code": "28867"
}


### Login
POST localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "username": "bigmangcom@gmail.com",
  "password": "12345"
}

> {% client.global.set("jwt", response.body.jwt); %}
